In [2]:
import pandas as pd

In [3]:
df=pd.read_csv("FashionDataset.csv")

In [4]:
## Removing Duplicates
df=df.drop_duplicates()
## Rows after removing duplicate
df.shape

(29427, 8)

In [5]:
## Checking the datatype of the column
df.dtypes

Unnamed: 0     int64
BrandName     object
Deatils       object
Sizes         object
MRP           object
SellPrice     object
Discount      object
Category      object
dtype: object

In [6]:
##Checking the Null values(But data has 'NaN' as string)
df.isnull().sum()

Unnamed: 0    0
BrandName     0
Deatils       0
Sizes         0
MRP           0
SellPrice     0
Discount      0
Category      0
dtype: int64

In [7]:
##Striping of the unessary part
df["MRP"]=df["MRP"].str.strip("Rs\n")

In [8]:
df.head(5)

,Unnamed: 0,BrandName,Deatils,Sizes,MRP,SellPrice,Discount,Category
0,0,life,solid cotton blend collar neck womens a-line d...,"Size:Large,Medium,Small,X-Large,X-Small",1699,849,50% off,Westernwear-Women
1,1,only,polyester peter pan collar womens blouson dres...,"Size:34,36,38,40",3499,2449,30% off,Westernwear-Women
2,2,fratini,solid polyester blend wide neck womens regular...,"Size:Large,X-Large,XX-Large",1199,599,50% off,Westernwear-Women
3,3,zink london,stripes polyester sweetheart neck womens dress...,"Size:Large,Medium,Small,X-Large",2299,1379,40% off,Westernwear-Women
4,4,life,regular fit regular length denim womens jeans ...,"Size:26,28,30,32,34,36",1699,849,50% off,Westernwear-Women

In [9]:
## changing the data type 
df['MRP']=pd.to_numeric(df['MRP'],errors='coerce')

In [10]:
## checking the null value in MRP column
df['MRP'].isnull().sum()

np.int64(7014)

In [12]:
## Creating the new Column and replacing null
df['MRP_'] = df['MRP'].fillna(df.groupby('Category')['MRP'].transform('mean'))

In [ ]:
##Droping the mrp column
df.drop('MRP',axis=1,inplace=True)

In [14]:
## discount
df['Discount']=df['Discount'].str.strip("% off")

In [15]:
df['Discount']=pd.to_numeric(df['Discount'],errors='coerce')

In [16]:
df['Discount_percent']=df['Discount'].fillna(
    df.groupby('BrandName')['Discount'].transform('median')
    ).fillna(0)

In [17]:
df.drop('Discount',axis=1,inplace=True)

In [18]:
## SellPrice
df['SellPrice']=pd.to_numeric(df['SellPrice'],errors='coerce')

In [19]:
df['SellPrice_']=df['SellPrice'].fillna(df['MRP_']*(df['Discount_percent']/100))

In [20]:
df.drop('SellPrice',axis=1,inplace=True)

In [ ]:
## Cheaking the Category Column
df['Category'].unique()

array(['Westernwear-Women', 'Indianwear-Women',
       'Lingerie&Nightwear-Women', 'Footwear-Women', 'Watches-Women',
       'Fragrance-Women', 'Jewellery-Women'], dtype=object)

In [22]:
## Replacing the unessary part and renaming the column
df['Category']=df['Category'].str.replace('-Women','')

In [23]:
df.rename(columns={'Category':'Womens_Category'},inplace=True)

In [ ]:
## Droping the UnNamed column
df.drop('Unnamed: 0',axis=1,inplace=True)

In [25]:
df['Sizes'].unique()

array(['Size:Large,Medium,Small,X-Large,X-Small', 'Size:34,36,38,40',
       'Size:Large,X-Large,XX-Large', ..., 'Size:3,8', 'Size:36,41',
       'Size:4,4.5,8.5'], shape=(1172,), dtype=object)

In [ ]:
## Replacing the string Nan NaN and fill with pd.NA(actual null)
df['Sizes']=df['Sizes'].replace(['nan','NAN','Nan',''],pd.NA)

In [27]:
## Filling the na with free size as as the data of null is too large we can not delete
df['Sizes']=df['Sizes'].fillna('Free Size')

In [ ]:
## checking the data
df.head(10)

,BrandName,Deatils,Sizes,Womens_Category,MRP_,Discount_percent,SellPrice_
0,life,solid cotton blend collar neck womens a-line d...,"Size:Large,Medium,Small,X-Large,X-Small",Westernwear,1699.0,50.0,849.0
1,only,polyester peter pan collar womens blouson dres...,"Size:34,36,38,40",Westernwear,3499.0,30.0,2449.0
2,fratini,solid polyester blend wide neck womens regular...,"Size:Large,X-Large,XX-Large",Westernwear,1199.0,50.0,599.0
3,zink london,stripes polyester sweetheart neck womens dress...,"Size:Large,Medium,Small,X-Large",Westernwear,2299.0,40.0,1379.0
4,life,regular fit regular length denim womens jeans ...,"Size:26,28,30,32,34,36",Westernwear,1699.0,50.0,849.0
5,kraus,wide ankle length cotton womens jeans - light ...,"Size:26,28,30,32,34",Westernwear,1795.0,10.0,1615.0
6,life,printed cotton blend collared womens regular d...,"Size:Large,Medium,Small,X-Large,X-Small",Westernwear,1299.0,50.0,649.0
7,fratini,embroidered wide neck polyester womens regular...,Size:XX-Large,Westernwear,1299.0,50.0,649.0
8,rare,floral polyester v neck womens flared dress - ...,"Size:Large,Medium,Small,X-Large",Westernwear,2099.0,60.0,839.0
9,rare,checks cotton boat neck womens regular top - b...,"Size:Medium,Small,X-Large",Westernwear,1499.0,60.0,599.0

In [29]:
df=df.replace(['Nan','nan',''],pd.NA)

In [30]:
df=df.dropna()

In [31]:
df = df.reset_index(drop=True)

In [32]:
df.shape

(29420, 7)